인프라 기본 모델 추가
duckie-team/duckie-app pull request #27
Opened 2022-10-12 02:38 UTC by jisungbin

## Issue

- close #ISSUE_NUMBER

## Overview (Required)

-

## Screenshot

Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2022-10-12 02:53 UTC, jisungbin commented
@riflockle7 @goddoro @cv-jaeha @EvergreenTree97 @limsaehyun 보시고 머지해도 될 때 마지막으로 리뷰하시는 분이 머지 해주세용

2022-10-12 12:24 UTC, goddoro approved these changes

2022-10-12 12:43 UTC, cv-jaeha commented
저희 MVP로 갈려면 badge 같은거 빼야하지 않나요 ?

2022-10-12 12:55 UTC, cv-jaeha commented
만약에 MVP 반영할거면 아래 변수 빼주세요..
User : 컬렉션
ChatRoom : 채팅유형 중 오픈채팅
ChatData : 수정 여부
Comment : 상위 댓글 id
FeedScore : 머문시간

만약 나중 생각해서 남겨두실거면 아래도 추가해주세요.
[time_check Table](https://www.notion.so/jisungbin/DB-3bb347e418ff42e6a25920c1a4f4e3cc#85ce9da613254589b23bb529e0ee993f)

2022-10-12 12:56 UTC, cv-jaeha approved these changes
만약에 MVP 반영할거면 아래 변수 빼주세요..
User : 컬렉션
ChatRoom : 채팅유형 중 오픈채팅
ChatData : 수정 여부
Comment : 상위 댓글 id
FeedScore : 머문시간

만약 나중 생각해서 남겨두실거면 아래도 추가해주세요.
[time_check Table](https://www.notion.so/jisungbin/DB-3bb347e418ff42e6a25920c1a4f4e3cc#85ce9da613254589b23bb529e0ee993f)

2022-10-12 12:58 UTC, cv-jaeha requested changes
만약에 MVP 반영할거면 아래 변수 빼주세요..
User : 컬렉션
ChatRoom : 채팅유형 중 오픈채팅
ChatData : 수정 여부
Comment : 상위 댓글 id
FeedScore : 머문시간

만약 나중 생각해서 남겨두실거면 아래도 추가해주세요.
[time_check Table](https://www.notion.so/jisungbin/DB-3bb347e418ff42e6a25920c1a4f4e3cc#85ce9da613254589b23bb529e0ee993f)

2022-10-12 15:48 UTC, EvergreenTree97 approved these changes

2022-10-12 16:11 UTC, EvergreenTree97 commented on domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/Feed.kt
> +    val isHidden: Boolean,
Feed에 숨김 사라져서 삭제해야합니다

2022-10-12 23:26 UTC, jisungbin commented on domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/Feed.kt
> +    val isHidden: Boolean,
https://sungbinland.slack.com/archives/C03CM18M529/p1665597623158669

2022-10-12 23:27 UTC, jisungbin commented
> Member

[슬랙](https://sungbinland.slack.com/archives/C03CM18M529/p1665597623158669)으로 답변 드렸습니다!

2022-10-13 00:40 UTC, riflockle7 approved these changes

2022-10-13 03:35 UTC, cv-jaeha approved these changes

2022-10-13 03:36 UTC, merged

2022-10-13 05:05 UTC, jisungbin commented
👍